### ISSUE TITLE
problem in using jar file in keycloak v16.1.1

### ISSUE THREAD

**Issue by mjk14** [FX-HAO/keycloak-phone-authenticator-yuntongxun-sms#6]
Hi. I can compile the project successfully and copy it to /providers of keycloak container but when restart keycloak container, I see this error and exit keycloak container. I am using keycloak v 16.1.1 and postgres v 13.2 . my docker compose configs for keycloak:

keycloak:
    depends_on:
      - postgres
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin 
      KEYCLOAK_LOGLEVEL: ALL
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_STATISTICS: all
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'
    image: jboss/keycloak:16.1.1
    ports:
      #- "18443:8443"
      - "18080:8080"
      - "8787:8787"
      #- "19990:9990"
    restart: unless-stopped
    networks:
      - local-keycloak
    volumes:
      - keycloak_home_volume:/opt/jboss/keycloak
      - keycloak_themes_volume:/opt/jboss/keycloak/themes
      
    error message: 
    
    05:25:09,978 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "metrics")]): java.lang.NullPointerException
	at org.wildfly.extension.metrics@26.0.1.Final//org.wildfly.extension.metrics.MetricsSubsystemAdd$2.execute(MetricsSubsystemAdd.java:91)
	at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:1045)
	at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:777)
	at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:466)
	at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1427)
	at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:550)
	at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:554)
	at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:516)
	at org.jboss.as.server@18.0.4.Final//org.jboss.as.server.ServerService.boot(ServerService.java:461)
	at org.jboss.as.server@18.0.4.Final//org.jboss.as.server.ServerService.boot(ServerService.java:414)
	at org.jboss.as.controller@18.0.4.Final//org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:455)
	at java.base/java.lang.Thread.run(Thread.java:829)

05:25:09,989 ERROR [org.jboss.as.server] (ServerService Thread Pool -- 45) WFLYSRV0022: Deploy of deployment "keycloak-server.war" was rolled back with no failure message

@FX-HAO

**Comment by fuxinhao-crypto** [comment]
I just tested building this with Keycloak v16.1.1 and it worked great. 
You can't just put the jar files into the `/providers` folder. please follow this documentation to [register a provider using modules](https://www.keycloak.org/docs/13.0/server_development/#register-a-provider-using-modules). Or you can take a look at my [example Dockerfile](https://github.com/FX-HAO/keycloak-phone-authenticator/tree/master/examples).

**Comment by FX-HAO** [comment]
I just tested building this with Keycloak v16.1.1 and it worked great. 
You can't just put the jar files into the `/providers` folder. please follow this documentation to [register a provider using modules](https://www.keycloak.org/docs/13.0/server_development/#register-a-provider-using-modules). Or you can take a look at my [example Dockerfile](https://github.com/FX-HAO/keycloak-phone-authenticator/tree/master/examples).

**Comment by FX-HAO** [comment]
> Providers are registered with the server by simply copying them to the providers directory.
If your provider needs additional dependencies not already provided by Keycloak copy these to the providers directory.
After registering new providers or dependencies Keycloak needs to be re-built with the kc.[sh|bat] build command.

I just noticed that `Keycloak v17` has a new deployment approach. I haven't tested it, but you can try it. (seems you still need to use jboss-cli script to register the modules since you're using keycloak v16)
